# Generated by Django 4.2.7 on 2025-11-25 15:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_examen', models.DateField(verbose_name='Fecha del Examen')),
                ('numero_prescripcion', models.CharField(help_text='Número único generado automáticamente', max_length=20, unique=True, verbose_name='Número de Prescripción')),
                ('od_esfera', models.DecimalField(decimal_places=2, help_text='Ojo Derecho - Esfera (-20.00 a +20.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(-20.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='OD Esfera')),
                ('od_cilindro', models.DecimalField(decimal_places=2, default=0.0, help_text='Ojo Derecho - Cilindro (-6.00 a +6.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(-6.0), django.core.validators.MaxValueValidator(6.0)], verbose_name='OD Cilindro')),
                ('od_eje', models.PositiveIntegerField(default=0, help_text='Ojo Derecho - Eje (0° a 180°)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='OD Eje')),
                ('os_esfera', models.DecimalField(decimal_places=2, help_text='Ojo Izquierdo - Esfera (-20.00 a +20.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(-20.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='OS Esfera')),
                ('os_cilindro', models.DecimalField(decimal_places=2, default=0.0, help_text='Ojo Izquierdo - Cilindro (-6.00 a +6.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(-6.0), django.core.validators.MaxValueValidator(6.0)], verbose_name='OS Cilindro')),
                ('os_eje', models.PositiveIntegerField(default=0, help_text='Ojo Izquierdo - Eje (0° a 180°)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='OS Eje')),
                ('adicion', models.DecimalField(blank=True, decimal_places=2, help_text='Para presbicia (0.00 a +4.00)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='Adición')),
                ('distancia_pupilar', models.PositiveIntegerField(blank=True, help_text='Distancia entre pupilas en milímetros', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(80)], verbose_name='Distancia Pupilar (mm)')),
                ('agudeza_visual_od', models.CharField(blank=True, help_text='Ej: 20/20, 20/40', max_length=10, verbose_name='Agudeza Visual OD')),
                ('agudeza_visual_os', models.CharField(blank=True, help_text='Ej: 20/20, 20/40', max_length=10, verbose_name='Agudeza Visual OS')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del examen, recomendaciones especiales', verbose_name='Observaciones Médicas')),
                ('tipo_lente_recomendado', models.CharField(blank=True, help_text='Ej: Monofocal, Bifocal, Progresivo', max_length=50, verbose_name='Tipo de Lente Recomendado')),
                ('vigente', models.BooleanField(default=True, help_text='Las prescripciones tienen vigencia de 2 años', verbose_name='Vigente')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='pacientes.paciente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesional que realiza el examen')),
            ],
            options={
                'verbose_name': 'Prescripción Oftalmológica',
                'verbose_name_plural': 'Prescripciones Oftalmológicas',
                'db_table': 'prescripciones',
                'ordering': ['-fecha_examen', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(max_length=100)),
                ('valor_nuevo', models.CharField(max_length=100)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('prescripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='prescripciones.prescripcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'db_table': 'historial_cambios_prescripciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='prescripcion',
            index=models.Index(fields=['paciente', '-fecha_examen'], name='prescripcio_pacient_814ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescripcion',
            index=models.Index(fields=['numero_prescripcion'], name='prescripcio_numero__f83fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='prescripcion',
            index=models.Index(fields=['vigente', '-fecha_examen'], name='prescripcio_vigente_bda60f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescripcion',
            index=models.Index(fields=['profesional', '-fecha_registro'], name='prescripcio_profesi_efba7b_idx'),
        ),
    ]
