# Generated by Django 4.2.7 on 2025-11-21 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('RC', 'Registro Civil')], default='CC', max_length=2, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(help_text='Número único de identificación del paciente', max_length=20, unique=True, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('observaciones', models.TextField(blank=True, help_text='Información médica relevante del paciente', verbose_name='Observaciones Médicas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['numero_documento'], name='pacientes_numero__14d398_idx'), models.Index(fields=['nombres', 'apellidos'], name='pacientes_nombres_739be1_idx'), models.Index(fields=['fecha_registro'], name='pacientes_fecha_r_22bfaf_idx')],
            },
        ),
    ]
