# Generated by Django 4.2.7 on 2025-11-25 16:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Montura Metal Dorada, Lente Antireflejo', max_length=200)),
                ('categoria', models.CharField(choices=[('MONTURA', 'Montura'), ('LENTE', 'Lente'), ('ACCESORIO', 'Accesorio'), ('LIMPIEZA', 'Producto de Limpieza'), ('ESTUCHE', 'Estuche'), ('OTROS', 'Otros')], help_text='Tipo de producto', max_length=20)),
                ('codigo', models.CharField(blank=True, help_text='Código del producto (opcional, principalmente para lentes)', max_length=50, null=True, unique=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio al que compraste el producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio al que vendes el producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario')),
                ('stock_minimo', models.PositiveIntegerField(default=1, help_text='Cantidad mínima antes de hacer pedido')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el producto está disponible para venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['categoria'], name='productos_p_categor_15e07f_idx'), models.Index(fields=['codigo'], name='productos_p_codigo_bbe51f_idx'), models.Index(fields=['activo'], name='productos_p_activo_31f808_idx')],
            },
        ),
    ]
